#!/bin/bash
#
# Starts, stops and monitors wildfly for comand-ui and admin.
#
# Author: David Mittelstaedt  <david.mittelstaedt@dataport.de>
# Date: 2017-11-23

# Set variables
# Full path to the instance directory
JBOSS_BASE_DIR=/opt/wildfly-8.2.1.Final/standalone
# Ip address
IP_ADDRESS=127.0.0.1
# Port offset
PORT_OFFSET=1000
# Current directory
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$CURRENT_DIR/gen-wildfly $JBOSS_BASE_DIR $IP_ADDRESS $PORT_OFFSET $1 $2

exit $?
