#!/bin/bash
#
# Starts, stops and monitors Apache HTTPD.
#
# Requires one argument start/stop/status.
#
# Author: David Mittelstaedt  <david.mittelstaedt@dataport.de>
# Date: 2017-10-26

# Set constant variables
# Full path to apache base dir
APACHE_BASE_DIR=/opt/apache-httpd-2.4.29
PORT=8080
RC=1

# Check status of Apache HTTPD. Return 0 if Apache HTTPD is running. Return 1 if not.
check_status () {
    is_port=$(netstat -tuln | grep 8081)
    if [ ! -z "$is_port" ] && [ -f $APACHE_BASE_DIR/logs/httpd.pid ]; then
      return 0
    else
      return 1
    fi
}

case "$1" in
  start)
    echo "Starting Apache HTTPD $PORT"
    check_status
    if [ $? != 0 ]; then
      $APACHE_BASE_DIR/bin/apachectl start
      if [ $? == 0 ]; then
        echo "Apache HTTPD successfully started"
        RC=0
      else
        echo "Apache HTTPD not started"
        RC=1
      fi
    else
      echo "Apache is already running"
      RC=1
    fi
  ;;
  status)
    echo "Checking for Apache HTTPD $PORT"
    check_status
    if [ $? == 0 ]; then
      echo "Apache HTTPD is running"
      RC=0
    else
      echo "Apache HTTPD is not running"
      RC=1
    fi
  ;;
  stop)
    echo "Shutting down Apache HTTPD $PORT"
    check_status
    if [ $? == 0 ]; then
      $APACHE_BASE_DIR/bin/apachectl stop
      if [ $? == 0 ]; then
        echo "Apache HTTPD successfully stopped"
        RC=0
      else
        echo "Apache HTTPD not sopped"
        RC=1
      fi
    else
      echo "Apache HTTPD is not running"
      RC=1
    fi
  ;;
esac

exit $RC
