#!/bin/sh
#
# Starts, stops and monitors apache tomcat
#
# Author: David Mittelstaedt  <david.mittelstaedt@dataport.de>
# Date: 2017-09-19

if [ ! -d $CATALINA_HOME ]; then
   echo "Apache Tomcat is not installed properly."
   exit 1
fi

case "$1" in
  start)
        echo "Starting Apache Tomcat "
        pid=`ps axww | grep org.apache.catalina.startup.Bootstrap | grep -v grep | awk '{print $1}'`
        if [ ! -z $pid ]; then
            echo "Apache Tomcat is already running"
        else
            $CATALINA_HOME/bin/startup.sh #>/dev/null 2>&1
        fi
        ;;
  stop)
        echo "Shutting down Apache Tomcat "
        $CATALINA_HOME/bin/shutdown.sh #>/dev/null 2>&1
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  status)
        echo "Checking for service Apache Tomcat "
        i=`ps axww | grep org.apache.catalina.startup.Bootstrap | grep -v grep | wc -l`
        if test $i = 0; then
             echo "Apache Tomcat is not running"
        else
             echo "Apache Tomcat is running"
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

exit
